package com.kangaroo;

import com.kangaroo.core.Feature;
import com.kangaroo.color.ColourFeature;
import com.kangaroo.ml.GbmModel;
import com.kangaroo.ml.Models;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import java.io.BufferedReader;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Proves that the pure-Java gradient-boosting engine reproduces the reference LightGBM
 * implementation exactly.
 *
 * <p>This is the test that converts "I ported a model" into "I proved I ported a model". The
 * vectors in {@code testdata/} are generated by {@code tools/generate_parity_vectors.py} against
 * the real LightGBM library and deliberately concentrate on the places a port goes wrong: exactly
 * on every split threshold in the model, one ULP either side of each, the missing-value sentinel,
 * and rows outside the range the model was trained on.
 *
 * <p>The tolerance is 1e-9 on the probability, which for a softmax over double-precision raw scores
 * is at the level of the last couple of bits. Anything looser would let a genuine mis-port through.
 */
class GbmParityTest {

    /** Probabilities must agree to here. Tighter than any clinical decision boundary by many orders. */
    private static final double TOLERANCE = 1e-9;

    @Test
    @DisplayName("clinical head is bit-parity with LightGBM over 6272 adversarial vectors")
    void clinicalParity() throws IOException {
        assertParity(Path.of("testdata", "gbm_parity_clinical.tsv"),
                Models.clinical(), Feature.COUNT, 3);
    }

    @Test
    @DisplayName("jaundice head is bit-parity with LightGBM over 17798 adversarial vectors")
    void jaundiceParity() throws IOException {
        assertParity(Path.of("testdata", "gbm_parity_jaundice.tsv"),
                Models.jaundice(), ColourFeature.COUNT, 5);
    }

    @Test
    @DisplayName("best_iteration is honoured: the models use fewer trees than the files contain")
    void honoursBestIteration() {
        GbmModel clinical = Models.clinical();
        assertEquals(33, clinical.usedIterations(),
                "clinical head should score exactly the 33 iterations early stopping selected");
        assertEquals(99, clinical.usedTrees());

        GbmModel jaundice = Models.jaundice();
        assertEquals(102, jaundice.usedIterations());
        assertEquals(510, jaundice.usedTrees());
        assertTrue(jaundice.totalTrees() >= jaundice.usedTrees(),
                "a model file never contains fewer trees than it uses");
    }

    @Test
    @DisplayName("feature order in the shipped model files matches the enums in the code")
    void featureOrderMatches() {
        Models.clinical().requireFeatureOrder(Feature.modelNames());
        Models.jaundice().requireFeatureOrder(ColourFeature.modelNames());
    }

    private static void assertParity(Path file, GbmModel model, int nFeatures, int nClasses)
            throws IOException {
        assertTrue(Files.exists(file),
                "parity vectors missing at " + file.toAbsolutePath()
                        + " - regenerate with: python tools/generate_parity_vectors.py");

        int rows = 0;
        double worst = 0;
        int worstRow = -1;
        int argmaxMismatches = 0;

        try (BufferedReader r = Files.newBufferedReader(file, StandardCharsets.UTF_8)) {
            String line;
            while ((line = r.readLine()) != null) {
                if (line.isBlank() || line.startsWith("#")) continue;
                String[] parts = line.split("\t");
                assertEquals(nFeatures + nClasses, parts.length,
                        "malformed parity row " + rows);

                double[] x = new double[nFeatures];
                for (int i = 0; i < nFeatures; i++) {
                    // Parsed as float then widened, exactly as the reference received them.
                    x[i] = Float.parseFloat(parts[i]);
                }
                double[] expected = new double[nClasses];
                for (int c = 0; c < nClasses; c++) {
                    expected[c] = Double.parseDouble(parts[nFeatures + c]);
                }

                double[] actual = model.predict(x);
                assertEquals(nClasses, actual.length);

                for (int c = 0; c < nClasses; c++) {
                    double delta = Math.abs(actual[c] - expected[c]);
                    if (delta > worst) {
                        worst = delta;
                        worstRow = rows;
                    }
                }
                if (argmax(actual) != argmax(expected)) argmaxMismatches++;
                rows++;
            }
        }

        assertTrue(rows > 1000, "expected a substantial vector set, found " + rows);
        assertEquals(0, argmaxMismatches,
                "the Java engine picked a different class on " + argmaxMismatches + " of " + rows + " rows");
        assertTrue(worst <= TOLERANCE,
                String.format("max probability deviation %.3e exceeded tolerance %.1e at row %d over %d rows",
                        worst, TOLERANCE, worstRow, rows));

        System.out.printf("  %s: %d vectors, max deviation %.3e%n", file.getFileName(), rows, worst);
    }

    private static int argmax(double[] v) {
        int a = 0;
        for (int i = 1; i < v.length; i++) if (v[i] > v[a]) a = i;
        return a;
    }
}
