package com.kangaroo.i18n;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.MissingResourceException;
import java.util.ResourceBundle;

/**
 * Localisation.
 *
 * <p>Literacy is not assumed anywhere in this product, and neither is English. The languages listed
 * in {@link #SUPPORTED} are chosen to cover the regions carrying most of the world's neonatal
 * mortality, not the regions carrying most of its software budget.
 *
 * <p>Two distinct things are localised and they work differently. The interface strings are
 * {@link ResourceBundle} catalogues, translated by people and shipped in the JAR. The action plan
 * is generated by the language model in the caregiver's language, which is why
 * {@link #languageName} exists — the model is told the language by name, in English, because that
 * is what it responds to most reliably.
 */
public final class Messages {

    private Messages() {}

    /** A supported language: its tag, its English name, its endonym, and whether it reads right to left. */
    public record Language(String tag, String englishName, String endonym, boolean rightToLeft) {
        public Locale locale() {
            return Locale.forLanguageTag(tag);
        }
    }

    /**
     * The shipped languages.
     *
     * <p>Ordered by the neonatal mortality burden of the populations that speak them, which is why
     * Hausa and Amharic appear ahead of languages with far more total speakers.
     */
    public static final List<Language> SUPPORTED = List.of(
            new Language("en", "English", "English", false),
            new Language("fr", "French", "Français", false),
            new Language("sw", "Swahili", "Kiswahili", false),
            new Language("ha", "Hausa", "Hausa", false),
            new Language("am", "Amharic", "አማርኛ", false),
            new Language("hi", "Hindi", "हिन्दी", false),
            new Language("bn", "Bengali", "বাংলা", false),
            new Language("ur", "Urdu", "اردو", true),
            new Language("ar", "Arabic", "العربية", true),
            new Language("pt", "Portuguese", "Português", false),
            new Language("es", "Spanish", "Español", false),
            new Language("id", "Indonesian", "Bahasa Indonesia", false));

    private static final Map<String, Language> BY_TAG = index();

    private static Map<String, Language> index() {
        Map<String, Language> m = new LinkedHashMap<>();
        for (Language l : SUPPORTED) m.put(l.tag(), l);
        return Map.copyOf(m);
    }

    private static final String BUNDLE = "i18n.kangaroo";

    /** The English name of a language, for telling the model which one to write in. */
    public static String languageName(Locale locale) {
        Language l = BY_TAG.get(locale.getLanguage());
        return l != null ? l.englishName() : locale.getDisplayLanguage(Locale.ENGLISH);
    }

    public static boolean rightToLeft(Locale locale) {
        Language l = BY_TAG.get(locale.getLanguage());
        return l != null && l.rightToLeft();
    }

    public static boolean supported(String tag) {
        return tag != null && BY_TAG.containsKey(tag.toLowerCase(Locale.ROOT));
    }

    /** Parse a language tag, falling back to English rather than to the machine's own locale. */
    public static Locale parse(String tag) {
        if (tag == null || tag.isBlank()) return Locale.ENGLISH;
        String primary = tag.split("[-_]")[0].toLowerCase(Locale.ROOT);
        return BY_TAG.containsKey(primary) ? Locale.forLanguageTag(primary) : Locale.ENGLISH;
    }

    /**
     * Look up an interface string.
     *
     * <p>A missing key returns the key itself rather than throwing. A clinical assessment must not
     * fail because a translator has not reached one label yet, and an untranslated key is visible
     * in the interface, which is the fastest way to get it noticed and fixed.
     */
    public static String get(Locale locale, String key) {
        try {
            return ResourceBundle.getBundle(BUNDLE, locale).getString(key);
        } catch (MissingResourceException e) {
            try {
                return ResourceBundle.getBundle(BUNDLE, Locale.ENGLISH).getString(key);
            } catch (MissingResourceException e2) {
                return key;
            }
        }
    }

    public static String get(Locale locale, String key, Object... args) {
        return java.text.MessageFormat.format(get(locale, key), args);
    }

    /** Every string in a locale, for the browser client to render entirely offline. */
    public static Map<String, String> catalogue(Locale locale) {
        Map<String, String> out = new LinkedHashMap<>();
        try {
            ResourceBundle english = ResourceBundle.getBundle(BUNDLE, Locale.ENGLISH);
            ResourceBundle target = ResourceBundle.getBundle(BUNDLE, locale);
            for (String key : english.keySet()) {
                out.put(key, target.containsKey(key) ? target.getString(key) : english.getString(key));
            }
        } catch (MissingResourceException e) {
            // No catalogue at all is survivable: the client falls back to its built-in English.
        }
        return Map.copyOf(out);
    }
}
