#!/usr/bin/env bash
#
# Produces build.log: the committed, unedited proof that Kangaroo compiles and runs on Java 26.
#
# The contest rules ask for either a build file targeting 26 or a log showing the commands used.
# Kangaroo ships both, and this script generates the second one so it cannot drift from reality --
# every line in build.log is real output from a real run, captured here rather than typed by hand.
#
# Run from the repository root:  ./packaging/build-log.sh
set -uo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"

toolchain="$(dirname "$root")/.toolchain"
if [ -d "$toolchain/jdk-26.0.1+8" ]; then
  export JAVA_HOME="$toolchain/jdk-26.0.1+8"
  export PATH="$JAVA_HOME/bin:$PATH"
fi

log="$root/build.log"

say() { printf '%s\n' "$*" | tee -a "$log"; }
run() {
  say ""
  say "\$ $*"
  say ""
  "$@" 2>&1 | tee -a "$log"
  local status=${PIPESTATUS[0]}
  say ""
  say "[exit status: $status]"
  return $status
}

: > "$log"

say "==============================================================================="
say " Kangaroo - Java 26 build and run log"
say ""
say " Generated by packaging/build-log.sh. Unedited."
say " Date: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
say " Host: $(uname -s) $(uname -m)"
say "==============================================================================="

say ""
say "-------------------------------------------------------------------------------"
say " 1. The toolchain"
say "-------------------------------------------------------------------------------"
run java -version
run javac -version

say ""
say "-------------------------------------------------------------------------------"
say " 2. Compile with an explicit --release 26"
say ""
say "    Not 'whatever JAVA_HOME points at' -- an explicit release target, so the"
say "    compiler rejects any API or language feature that is not in Java 26."
say "-------------------------------------------------------------------------------"

rm -rf target/build-log-classes
mkdir -p target/build-log-classes

# Relative paths throughout. javac's @argfile parser splits on whitespace, so an absolute path
# containing a space (which this checkout has) would be torn into several bogus arguments.
find src/main/java -name '*.java' > target/build-log-sources.txt
say ""
say "Source files: $(wc -l < target/build-log-sources.txt)"

run javac \
  --release 26 \
  --enable-preview \
  --add-modules jdk.incubator.vector \
  -Xlint:all,-preview,-serial,-this-escape \
  -d target/build-log-classes \
  @target/build-log-sources.txt

say ""
say "-------------------------------------------------------------------------------"
say " 3. Confirm the emitted class files really are Java 26 (major version 70)"
say "-------------------------------------------------------------------------------"
say ""
say "\$ javap -v -p -cp target/build-log-classes com.kangaroo.clinical.ImnciRule | head -4"
say ""
javap -v -p -cp target/build-log-classes com.kangaroo.clinical.ImnciRule 2>&1 \
  | head -n 4 | tee -a "$log"

say ""
say "-------------------------------------------------------------------------------"
say " 4. Run the single-file diagnostic (JEP 458 source launcher, no build tool)"
say ""
say "    Every JDK 26 feature Kangaroo depends on, executing and printing its result."
say "-------------------------------------------------------------------------------"
run java --enable-preview --add-modules jdk.incubator.vector "$root/tools/Check.java"

say ""
say "-------------------------------------------------------------------------------"
say " 5. Full build and test suite"
say "-------------------------------------------------------------------------------"
run ./mvnw -B clean package

say ""
say "-------------------------------------------------------------------------------"
say " 6. Run the packaged application and exercise it over HTTP"
say "-------------------------------------------------------------------------------"

port=8899
data="$root/target/build-log-data"
rm -rf "$data"

java --enable-preview --add-modules jdk.incubator.vector --enable-native-access=ALL-UNNAMED \
  -jar "$root/target/kangaroo.jar" --port "$port" --data "$data" > "$root/target/run.log" 2>&1 &
server_pid=$!

for _ in $(seq 1 40); do
  if curl -fsS "http://127.0.0.1:$port/api/status" > /dev/null 2>&1; then break; fi
  sleep 0.5
done

say ""
say "--- startup output ---"
cat "$root/target/run.log" | tee -a "$log"

say ""
say "\$ curl -s http://127.0.0.1:$port/api/assess -d '<a lethargic, non-feeding newborn>'"
say ""
curl -fsS -X POST "http://127.0.0.1:$port/api/assess" \
  -H 'Content-Type: application/json' \
  -d '{"mode":"chw","age_days":6,"weight_kg":2.9,"sex":"female","respiratory_rate":52,
       "intake_text":"Mother says the baby has been very sleepy since last night and is not feeding at all. No fever."}' \
  2>&1 | tee -a "$log"

say ""
say ""
say "\$ curl -s http://127.0.0.1:$port/api/jeps"
say ""
curl -fsS "http://127.0.0.1:$port/api/jeps" 2>&1 | tee -a "$log"

say ""
say ""
say "\$ curl -s http://127.0.0.1:$port/api/bench"
say ""
curl -fsS "http://127.0.0.1:$port/api/bench" 2>&1 | tee -a "$log"

kill "$server_pid" 2>/dev/null
wait "$server_pid" 2>/dev/null

say ""
say ""
say "==============================================================================="
say " End of log. Compiled with --release 26 and run on Java 26 throughout."
say "==============================================================================="

rm -rf "$root/target/build-log-classes" "$root/target/build-log-sources.txt" "$data"
echo "Wrote $log"
